name: Wails build

on:
  push:
    branches:
      - development
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"
  APP_VERSION: ${{ github.ref_name }}
  GIT_SHA: ${{ github.sha }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'gituserChrome'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.24.6'
          envs: |
            APP_VERSION=${{ env.APP_VERSION }}
            GIT_SHA=${{ env.GIT_SHA }}