// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['main']['App']['BrowserOpenURL'](arg1);
}

export function CheckConfigExists() {
  return window['go']['main']['App']['CheckConfigExists']();
}

export function CreateConfig() {
  return window['go']['main']['App']['CreateConfig']();
}

export function DeleteConfig() {
  return window['go']['main']['App']['DeleteConfig']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function IsGitInstalled() {
  return window['go']['main']['App']['IsGitInstalled']();
}

export function LoadWindowConfig() {
  return window['go']['main']['App']['LoadWindowConfig']();
}

export function OpenConfig() {
  return window['go']['main']['App']['OpenConfig']();
}

export function OpenProfiles() {
  return window['go']['main']['App']['OpenProfiles']();
}

export function ProcessGit() {
  return window['go']['main']['App']['ProcessGit']();
}

export function RemoveFromConfig(arg1) {
  return window['go']['main']['App']['RemoveFromConfig'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendtoApp() {
  return window['go']['main']['App']['SendtoApp']();
}

export function UpdateWindowConfig(arg1) {
  return window['go']['main']['App']['UpdateWindowConfig'](arg1);
}

export function ValidateConfig() {
  return window['go']['main']['App']['ValidateConfig']();
}

export function WriteToConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteToConfig'](arg1, arg2);
}
