// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowserOpenURL(arg1:string):Promise<void>;

export function CheckConfigExists():Promise<boolean>;

export function CreateConfig():Promise<void>;

export function DeleteConfig():Promise<void>;

export function GetOS():Promise<string>;

export function IsGitInstalled():Promise<boolean>;

export function LoadWindowConfig():Promise<main.Window>;

export function OpenConfig():Promise<void>;

export function OpenProfiles():Promise<void>;

export function ProcessGit():Promise<boolean>;

export function RemoveFromConfig(arg1:string):Promise<void>;

export function ResetConfig():Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SendtoApp():Promise<void>;

export function UpdateWindowConfig(arg1:main.Window):Promise<void>;

export function ValidateConfig():Promise<main.Config>;

export function WriteToConfig(arg1:string,arg2:any):Promise<void>;
